name: Test ApiDOM Validator

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test_github_action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: char0n/apidom-validate@main
        with:
          definition-file: ./.github/workflows/fixtures/openapi.json


